import Head from "next/head";
import Link from "next/link";
import { useRef } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const emailInputRef = useRef();

  const registrationHandler = (e) => {
    e.preventDefault();

    const enteredEmail = emailInputRef.current.value;

    fetch("/api/newsletter", {
      method: "POST",
      body: JSON.stringify({ email: enteredEmail }),
      headers: {
        "Content-Type": "application/json",
      },
    })
      .then((res) => res.json())
      .then((data) => console.log(data));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={registrationHandler}>
          <input
            ref={emailInputRef}
            name="email"
            type="email"
            id="email"
            placeholder="enter your email"
          />
        </form>
        <Link href="/comment">go to comment page</Link>
      </main>
    </div>
  );
}
